UNEMPLOYMENT_DATA_SOURCE = 'justin2028/unemployment-in-america-per-us-state'
TABLE1 = 'us_unemployment'
CRIME_DATA_SOURCE = 'mrayushagrawal/us-crime-dataset'
TABLE2 = 'us_crime'
DB = 'data/project_americas.db'
