name: Exercise Feedback

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Installing Required Libraries
      - name: Install Libraries
        id: install_libraries
        run: |
          python3 -m pip install -r requirements.txt

      # Run Tests
      - name: Run Tests
        id: run_tests
        run: |
          bash ./test.sh
